version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
  catalogdb:
    image: postgres:15
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
        context: .
        dockerfile: Services/Catalog/Catalog.API/Dockerfile
    # IMPORTANT: Ensure there is NO 'build' section here.

volumes:
  # This declares the volume so the override file can use it
  postgres_catalog: